add routes and question controller
Ch0k/test-guru pull request #10
Opened 2021-07-30 00:38 UTC by Ch0k

2021-07-30 06:47 UTC, BubuntuClu requested changes

2021-07-30 06:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2021-07-30 06:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @order.destroy
что за заказ?)

2021-07-30 06:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render inline: '<% Question.all.each do |question| %> <br> <%= question.body %> <% end %>'
все впоросы плохо показывать. вопросы привязаны к тесту, показывает только вопросы текущего теста

2021-07-30 06:47 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body,:test_id)
если будешь создавать через ассоциацию, а это рекомендуется делать, то параметр `test_id` надо убрать

2021-07-30 06:47 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form accept-charset="UTF-8" action="/tests/1/questions" method="post">
ты жестко привязал путь к id теста 1. а что будет если в системе не будет теста с таким id? этот параметр должен подставляться динамически из параметров

2021-07-30 06:47 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +  <input type="text" name="question[test_id]"/>
это здесь лишнее. при правильном написании кода, параметр теста в вопрос будет подставляться по ассоциации

2021-07-30 06:47 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
попробуй сделать этот ресурс вложенным в ресурс тестов `shallow: true`. посмотри как изменяться у тебя пути в `rake routes` после добаления этой опции

2021-07-30 09:41 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +    question = Question.create(question_params)
Окей

2021-07-30 09:42 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +    @order.destroy
Я это скопировал ) с другого своего проекта) Невнимательный )

2021-07-30 09:43 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body,:test_id)
Прото он так не сохранял в базу.

2021-07-30 09:44 UTC, Ch0k commented on app/views/questions/new.html.erb
> +<form accept-charset="UTF-8" action="/tests/1/questions" method="post">
В тексте урока написано, использовать жестко в ручную. Попрбую динамически

2021-07-30 09:44 UTC, Ch0k commented on app/views/questions/new.html.erb
> +  <input type="text" name="question[test_id]"/>
Сделаю

2021-07-31 09:48 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form accept-charset="UTF-8" action="/tests/1/questions" method="post">
>Идентификатор теста к которому принадлежит вопрос можно указать явно в составе URL значения атрибута action в тэге form

да, имеется в виду руками прописать значение параметра для ссылки, но не конретное значение, а чтобы оно бралось из параметра

2021-07-31 09:52 UTC, BubuntuClu requested changes

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id])
`@questions = @test.questions`
все просто. твой способ какой-то ультра сложный)

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test_id = Test.find(params[:test_id])
тут что-то с неймингом не то. ты же тут получаешь тест, а него его идентификатор

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id])
метод дублируется, надо вынести его в функцию/колбэк

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +      if question.save
ты выше уже сделал `create`, большого смысла тут от `save` уже нет. надо `create` заменить на `new`

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
этого не стоит сейчас делать. ты отдаешь всегда в одном формате ответ, не надо усложнять логику неподдерживаемым кодом

2021-07-31 09:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body,:test_id)
отсюда надо убрать параметр `test_id`, ты уже переделал на ассоциацию

2021-07-31 09:52 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form accept-charset="UTF-8" action="/tests/<%= @test %>/questions" method="post">
нейминг говорит о том что ты вставляешь сюда объект теста, а не его идентификатор. надо стараться писать очевидный код, который понятен просто при взгляде на него, без изучения контекста

2021-07-31 23:30 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +    @test = Test.find(params[:test_id])
=)

2021-08-02 19:36 UTC, merged