add views
Ch0k/test-guru pull request #11
Opened 2021-08-03 17:54 UTC by Ch0k

2021-08-03 18:45 UTC, BubuntuClu requested changes

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.new
```
def new
   @question = @test.questions.new
end
```

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :set_test_id,  only: %i[ destroy edit update]
такой метод тебе не нужен. ты можешь тест достать из вопроса

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      @test = Test.find(params[:test_id])
у тебя есть метод `set_test`, он прописан в колбэке. тут зачем находить тест еще раз?

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @test = @question.test
нужен ли тебе тест в редактирвоании вопроса? на вьюхе ты можешь достать тест через вопрос, если надо для роута

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def set_test_id
не нужный метод, стоит удалить

2021-08-03 18:45 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test_id = @test.id
зачем тебе это? используй на вьюхе просто `@test.id`

2021-08-03 18:45 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}"
возвращай тут сразу url-хэлпер link_to

2021-08-03 18:45 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +  def question_header
передавай сюда явно объект вопроса и используй на нем метод `new_record?/persisted?` чтобы понять какой текст выводить

2021-08-03 18:45 UTC, BubuntuClu commented on app/models/test.rb
>    scope :hard, -> {where(level: 5..Float::INFINITY)}
из метода list_category_order_title надо убрать `.where('categories.title = ? ', category)`, так как это уже есть в скоупе

2021-08-03 18:45 UTC, BubuntuClu commented on app/views/shared/_footer.html.erb
> +<%= Time.zone.now.year %>
это тоже в хэлпер надо вынести

2021-08-03 18:45 UTC, BubuntuClu commented on app/views/shared/_errors.html.erb
> +<% end %>
В IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2021-08-05 17:14 UTC, BubuntuClu requested changes

2021-08-05 17:14 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to test_url(@question.test.id), notice: 'Question was successfully delete.'
можно просто `redirect_to test_url(@question.test)`, рельса сама достанет id.

2021-08-05 17:14 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    "Create new #{@test.title} question" if @question.new_record?
```
if @question.new_record?
  "Create new #{@test.title} question"
else
  "Edit new #{@question.test.title} question"
end
```
зачем двойная проверка?

2021-08-05 17:14 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :list_category,-> (category) {joins('JOIN categories ON tests.category_id = categories.id')
ты не то сделал. из метода `list_category_order_title` надо было удалить, а ты из скоупа `list_category` удалил

2021-08-05 17:14 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= link_to 'Back', test_path(@question.test.id) %>
указывай куда сделать редирект без получения id

2021-08-05 17:14 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= link_to 'Back', test_path(@test.id) %>
указывай куда сделать редирект без получения id

2021-08-05 17:14 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= link_to 'Back', test_path(@test.id) %>
В IDE сделай настройку, чтобы добавлялась пустая строка в конец файла. Это исправит ворнинг на гитхабе

2021-08-05 17:14 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +  def year
что за год? плохой нейминг метода, слишком абстрактно

2021-08-05 17:14 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  #def set_test_id
ненужный код не надо комментировать, его надо сразу удалять

2021-08-05 19:11 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +    redirect_to test_url(@question.test.id), notice: 'Question was successfully delete.'
ok

2021-08-05 19:12 UTC, Ch0k commented on app/helpers/questions_helper.rb
> +    "Create new #{@test.title} question" if @question.new_record?
Так мне показалось надежнее

2021-08-05 19:12 UTC, Ch0k commented on app/models/test.rb
> +  scope :list_category,-> (category) {joins('JOIN categories ON tests.category_id = categories.id')
да, затупил

2021-08-05 19:12 UTC, Ch0k commented on app/views/questions/edit.html.erb
> +<%= link_to 'Back', test_path(@question.test.id) %>
ок

2021-08-05 19:13 UTC, Ch0k commented on app/views/questions/new.html.erb
> +<%= link_to 'Back', test_path(@test.id) %>
сделал. видать после перезаписи файлов строку добавит

2021-08-05 19:13 UTC, Ch0k commented on app/helpers/application_helper.rb
> +  def year
ясно

2021-08-05 19:13 UTC, Ch0k commented on app/controllers/questions_controller.rb
> +  #def set_test_id
ок

2021-08-07 22:15 UTC, merged