Test passenges
Ch0k/test-guru pull request #12
Opened 2021-08-18 06:21 UTC by Ch0k

2021-08-18 06:53 UTC, BubuntuClu requested changes

2021-08-18 06:53 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    #@answer = Answer.new
не стоти такое сохранять. это загрязняет код. удаляй и не тащи в репозиторий

2021-08-18 06:53 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    redirect_to tests complited?
зачем тут `completed?`

2021-08-18 06:53 UTC, BubuntuClu commented on app/controllers/user_tests_controller.rb
> +    @question = @user_test.test.questions
а это зачем делать? разве тебе тут что-то нужно от вопросов?

и проблема нейминга - `@question` один объект вопроса, а получаешь много `@user_test.test.questions` вопросов

2021-08-18 06:53 UTC, BubuntuClu commented on app/helpers/user_tests_helper.rb
> +  def success_rate
это метод модели

2021-08-18 06:53 UTC, BubuntuClu commented on app/helpers/user_tests_helper.rb
> +    if (@user_test.correct_questions_multiply_by_100)/@user_test.test_questions_count > 85
это тоже метод модели, который будет использовать другой метод модели

2021-08-18 06:53 UTC, BubuntuClu commented on app/helpers/user_tests_helper.rb
> +    if (@user_test.correct_questions_multiply_by_100)/@user_test.test_questions_count > 85
85 это магическое число, которое без контекста не понятно. помести тоже в модель(оно будет использовать в методе модели) и обзови понятно

2021-08-18 06:53 UTC, BubuntuClu commented on app/helpers/user_tests_helper.rb
> +      true
само сравнение и так возрвщает bool значение, для него не надо if делать

2021-08-18 06:53 UTC, BubuntuClu commented on app/models/answer.rb
> +    @quesiton = self.question
это тут не нужно

2021-08-18 06:53 UTC, BubuntuClu commented on app/views/user_tests/show.html.erb
> +  <%= unless @user_test.complited?
зачем тут эта проверка?

2021-08-19 19:51 UTC, Ch0k commented on app/controllers/answers_controller.rb
> +    #@answer = Answer.new
ok

2021-08-19 19:53 UTC, Ch0k commented on app/controllers/tests_controller.rb
> +    redirect_to tests complited?
ok

2021-08-19 20:27 UTC, Ch0k commented on app/controllers/user_tests_controller.rb
> +    @question = @user_test.test.questions
ok

2021-08-19 20:27 UTC, Ch0k commented on app/helpers/user_tests_helper.rb
> +  def success_rate
ok

2021-08-19 20:30 UTC, Ch0k commented on app/helpers/user_tests_helper.rb
> +    if (@user_test.correct_questions_multiply_by_100)/@user_test.test_questions_count > 85
ok

2021-08-19 20:31 UTC, Ch0k commented on app/helpers/user_tests_helper.rb
> +      true
ok

2021-08-19 20:39 UTC, Ch0k commented on app/models/answer.rb
> +    @quesiton = self.question
ok

2021-08-19 20:40 UTC, Ch0k commented on app/views/user_tests/show.html.erb
> +  <%= unless @user_test.complited?
Была ошибка , когда тест заканчивался не выполнялся метод @user_test.question_number. Сейчас все нормально

2021-08-20 06:54 UTC, BubuntuClu commented on app/models/user_test.rb
> +  def correct_questions_multiply_by_100
нууууу, не знаю. мне кадется, это слишком вырождено

2021-08-20 20:32 UTC, merged