Users
Ch0k/test-guru pull request #13
Opened 2021-08-23 11:45 UTC by Ch0k

2021-08-23 17:28 UTC, BubuntuClu requested changes

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
зачем тебе в куки сохранять почту?

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:user_id] = current_user&.id
зачем тебе в куку сохранить id пользователя, когда это есть уже в сессии?

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:user_url] = request.fullpath
что за `user_url`, звучит так как будто ведет на какой-то его профиль, а не то куда он хотел попасть. плохой нейминг.

и стоит сохранять этот путь только для тех, кто не авторизован

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      @url = cookies[:user_url]
зачем тут инстанс переменная? ты где-то вне этого метода используешь ее? зачем вообще переменная? ты же можешь `cookies[:user_url]` и без переменной

`redirect_to cookies[:good_naming] || root_path`

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
ты в каждом контроллере прописываешь этот метод, может его тогда вынести в ApplicationController?

2021-08-23 17:28 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user = current_user
тоже метод, который из одного места перекладывает в другое.

тебе метод `ser_user` уже не нужен, удали его и используй `current_user` метод, там где надо получить пользователя

2021-08-23 17:28 UTC, BubuntuClu commented on db/migrate/20210820204233_remove_password_from_users.rb
> +class RemovePasswordFromUsers < ActiveRecord::Migration[6.1]
все три миграции касаются одной таблицы. стоит объединить в одну миграцию, в которой будут удаляться ненужные строки и добавляться нужные

2021-08-23 17:28 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email", null: false
нет индекса уникальности в БД, а в модели есть. надо продублировать ограничение и на уровне БД

2021-08-23 17:28 UTC, BubuntuClu commented on config/routes.rb
> +  resources :sessions, only: %i[create]
`only: %i[create]` `only: :create`
придерживайся какого-то одного стиля написания кода. один и тот же кусок кода, у тебя выглядит по разному

2021-08-23 21:51 UTC, Ch0k commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
Это было в уроке

2021-08-23 21:55 UTC, Ch0k commented on app/controllers/application_controller.rb
> +    cookies[:user_id] = current_user&.id
ok

2021-08-23 22:03 UTC, Ch0k commented on app/controllers/sessions_controller.rb
> +      @url = cookies[:user_url]
ok

2021-08-23 22:06 UTC, Ch0k commented on app/controllers/tests_controller.rb
> +    @user = current_user
ok

2021-08-23 22:09 UTC, Ch0k commented on db/migrate/20210820204233_remove_password_from_users.rb
> +class RemovePasswordFromUsers < ActiveRecord::Migration[6.1]
ok

2021-08-23 22:10 UTC, Ch0k commented on config/routes.rb
> +  resources :sessions, only: %i[create]
ok

2021-08-23 22:13 UTC, Ch0k commented on db/schema.rb
>      t.string "email", null: false
ok

2021-08-23 22:15 UTC, Ch0k commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
не во всех контроллерах используется этот метод. Не используется в users , sessions

2021-08-24 07:02 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
для этих контроллеров отключи этот метод, отключение явно требуется реже, чем включение

2021-08-24 07:02 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
это хорошо, но ты это нигде не используешь, зачем тогда сохранять?

2021-08-28 08:41 UTC, merged